package br.com.antipoda.orbits.empresa.enums;

public enum Bonificacao {
    DESORBITACAO_RESPONSAVEL,
    BAIXO_RISCO_DE_COLISAO,
    SATELITE_ATIVO_E_REGULARIZADO,
    PLANO_DE_MITIGACAO_APROVADO,
    BAIXA_GERACAO_DE_LIXO_ESPACIAL,
    REGISTRO_ORBITAL_REGULAR,
    TRANSPARENCIA_DE_DADOS,
    PARTICIPACAO_EM_INICIATIVA_SUSTENTAVEL,
    CONFORMIDADE_REGULATORIA
}
