package br.com.antipoda.orbits.empresa.enums;

public enum Penalidade {
    ALTO_RISCO_DE_COLISAO,
    GERACAO_DE_LIXO_ESPACIAL,
    SATELITE_SEM_PLANO_DE_DESORBITACAO,
    REGISTRO_ORBITAL_IRREGULAR,
    FALTA_DE_TRANSPARENCIA,
    GERACAO_DE_FRAGMENTOS_ORBITAIS,
    DESCUMPRIMENTO_REGULATORIO,
    USO_SUSPEITO_DE_INFRAESTRUTURA_ESPACIAL,
    SATELITE_INATIVO_EM_ORBITA
}
